config/routes.rb
AlvicomTwitter::Application.routes.draw do
  root to: 'home#index'

  resources :users do
    member do
      get :following, :followers, :liked_microposts
      put :change_admin_right
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
    
  match '/help', to: 'home#help'
  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'  
  match '/users', to: 'users#index'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items, inner_window: 1, outer_window: 1 %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user"> <%= link_to feed_item.user.name, feed_item.user %> </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp"> Posted <%= time_ago_in_words(feed_item.created_at) %> ago. </span>
    <div>
        <% if signed_in? %>
        <div id="like_form_<%= feed_item.id %>" class="link">
                <% if feed_item.likeby?(current_user) %>
            <%= link_to "dislike", current_user.like_relationships.find_by_micropost_id(feed_item), method: :delete, remote: true %>
            <% else %>
            <%= link_to "like", likes_path(micropost_id: feed_item.id), method: :post, remote: true %>
            <% end %>
        </div>
        <% end %>
        <% if current_user?(feed_item.user) %>
        <div id="delete_micropost_form_<%= feed_item.id %>" class="link">
            <%= link_to "delete", feed_item, method: :delete,
            data: { confirm: "You sure?" },
            title: feed_item.content %>
        </div>
        <% end %>
        <div class="lastlink"/>
        <div id="user_avatars_<%= feed_item.id %>" class="user_avatars">
            <% feed_item.likers.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
            <% end %>
        </div>
    </div>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a href="<%= liked_microposts_user_path(@user) %>">
     <% if current_user?(@user) %>  
        <strong id="likes" class="stat">
     <% else %>
        <strong id="otheruser_likes" class="stat">
     <% end %>            
      <%= @user.liked_microposts.count %>
    </strong>
    likes
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>